[package]
name = "rusday"
version = "0.6.1"
authors = ["Johannes Christ <Johannes.christ@gmail.com>"]

[dependencies]
ansi_term = "0.10.2"
chrono = "0.4"
clap = "~2.29"
dirs = "~1.0.4"
isatty = "0.1.6"

[dependencies.rusqlite]
version = "0.14.0"
features = ["chrono"]
